#!/bin/bash

#scp *.so root@104.216.12.229:/usr/local/lib
scp *.so root@162.211.122.170:/usr/local/lib
#scp *.so root@104.216.12.230:/usr/local/lib
scp *.so root@162.211.122.171:/usr/local/lib
#scp *.so root@192.168.1.67:/usr/local/lib
scp *.so root@192.168.1.33:/usr/local/lib
#scp *.so root@192.168.1.143:/usr/local/lib
