#ifndef BLOCK_TYPES_NETWORK_DEVICE_BLOCK_H_
#define BLOCK_TYPES_NETWORK_DEVICE_BLOCK_H_

#include "BLOCK_DESCRIPTOR.h"

struct NETWORK_DEVICE_BLOCK; // An encrypted packet of the MTU capacity

const struct BLOCK_DESCRIPTOR DEFAULT_NETWORK_HEADER_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_NETWORK_DEVICE_LOCAL,
	BLOCK_OPTION_SEND,
	BLOCK_LATENCY_MODERATE
};

#endif // BLOCK_TYPES_NETWORK_DEVICE_BLOCK_H_
