#include "../HERMES.h"

// Generated by HOST and sent to both connecting parties

struct HERMES_SEED_BLOCK
{
	HERMES_DEVICE_BLOCK local_device;
	HERMES_DEVICE_BLOCK remote_device;
	unsigned long       Local_Key_Capacity;       // MTU
	unsigned long       Remote_Key_Capacity;      // MTU
	unsigned long       Local_Key_Seed_Capacity;  // in multiples of Local_Key_Capacity
	unsigned long       Remote_Key_Seed_Capacity; // in multiples of Remote_Key_Capacity
	char[]              Local_Key_Seed_Data;
	char[]              Remote_Key_Seed_Data;
};
