#ifndef FRAME_HEADER_BLOCK_H_
#define FRAME_HEADER_BLOCK_H_

#include "BLOCK_DESCRIPTOR.h"

struct FRAME_HEADER_BLOCK
{
	unsigned long Device_Index;
	unsigned long Buffer_Index;
};

const struct BLOCK_DESCRIPTOR DEFAULT_FRAME_HEADER_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_GAIA_ROOT,
	BLOCK_OPTION_SEND,
	BLOCK_LATENCY_MODERATE
};

#endif // FRAME_HEADER_BLOCK_H_
