.PHONY: protobuf_http_api_example

protobuf_http_api_example:
	make -f protobuf_http_api_example.mk

protobuf_http_api_example_clean:
	make -f protobuf_http_api_example.mk clean

protobuf_http_api_example_run:
	make -f protobuf_http_api_example.mk run