#ifndef GAIA_BLOCK_H_
#define GAIA_BLOCK_H_

#include "../../BLOCK_DESCRIPTOR.h"

struct GAIA_DATA_BLOCK; // Variable size command buffers

const struct BLOCK_DESCRIPTOR DEFAULT_GAIA_LOCAL_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_GAIA,
	BLOCK_OPTION_SEND,
	BLOCK_LATENCY_URGENT
};

const struct BLOCK_DESCRIPTOR DEFAULT_GAIA_REMOTE_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_GAIA,
	BLOCK_OPTION_SEND,
	BLOCK_LATENCY_URGENT
};

#endif // GAIA_BLOCK_H_
