#ifndef IDLE_BLOCK_H_
#define IDLE_BLOCK_H_

#include "BLOCK_DESCRIPTOR.h"

struct IDLE_BLOCK; // Empty

const struct BLOCK_DESCRIPTOR DEFAULT_IDLE_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_IDLE,
	BLOCK_OPTION_NONE,
	BLOCK_LATENCY_NEVER
};

#endif // IDLE_BLOCK_H_
