#ifndef HERMES_DEVICE_BLOCK_H_
#define HERMES_DEVICE_BLOCK_H_

#include "BLOCK_DESCRIPTOR.h"

struct HERMES_TRANSFER_LOG_BLOCK
{
	unsigned long Packet_Index;
	unsigned long Delivered_At;
};

const struct BLOCK_DESCRIPTOR DEFAULT_HERMES_DEVICE_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_HERMES_DEVICE,
	BLOCK_OPTION_SEND,
	BLOCK_LATENCY_MODERATE
};

#endif // HERMES_DEVICE_BLOCK_H_
