#ifndef WEB_SOCKET_SERVER_MASTER_H_
#define WEB_SOCKET_SERVER_MASTER_H_

#include <signal.h>
#include "NETWORK.h"
#include "../Utilities/KCONTEXT.h"

struct WEB_SOCKET_SERVER_MASTER {
	KCONTEXT *ctx;
	char name[MAX_NAME_SIZE];

	int lSocket;
};

bool Initialize_WEB_SOCKET_SERVER_MASTER(WEB_SOCKET_SERVER_MASTER*, KCONTEXT*, int);
void Set_Name_WEB_SOCKET_SERVER_MASTER(WEB_SOCKET_SERVER_MASTER*, char*);
bool Set_Recv_Timeout_WEB_SOCKET_SERVER_MASTER(WEB_SOCKET_SERVER_MASTER*, int, int);
bool Set_High_Priority_WEB_SOCKET_SERVER_MASTER(WEB_SOCKET_SERVER_MASTER*);
void Delete_WEB_SOCKET_SERVER_MASTER(WEB_SOCKET_SERVER_MASTER*);

#endif