#ifndef _SOCKET_SERVER_REGISTRY_H_
#define _SOCKET_SERVER_REGISTRY_H_

#include "ROOT_SOCKET_SERVER.h"

#define MAX_ROOT_SOCKETS 5

struct SOCKET_SERVER_REGISTRY {
	ROOT_SOCKET_SERVER root_sockets[MAX_ROOT_SOCKETS];
};

bool Initialize_SOCKET_SERVER_REGISTRY(SOCKET_SERVER_REGISTRY*);
void Delete_SOCKET_SERVER_REGISTRY(SOCKET_SERVER_REGISTRY*);

#endif