#ifndef GAIA_ROOT_DATA_BLOCK_H_
#define GAIA_ROOT_DATA_BLOCK_H_

#include "../../../BLOCK_DESCRIPTOR.h"

struct GAIA_ROOT_DATA_BLOCK
{
	BLOCK_DESCRIPTOR Descriptor; // Array
}

const struct BLOCK_DESCRIPTOR* const DEFAULT_GAIA_ROOT_BLOCK_DESCRIPTOR =
{
	BLOCK_TYPE_GAIA_ROOT,
	BLOCK_OPTION_SEND & BLOCK_OPTION_LATEST_COMMAND & BLOCK_OPTION_COMPRESS_COMMANDS,
	BLOCK_LATENCY_LOW
};

#endif // GAIA_ROOT_DATA_BLOCK_H_
