#ifndef ALIGNMENT_H_
#define ALIGNMENT_H_

#include <cmath>
#include "../GUI.h"

enum ALIGNMENT_1D {
	ALIGNMENT_BEGIN, ALIGNMENT_MIDDLE, ALIGNMENT_END
};
enum ALIGNMENT_2D {
	ALIGNMENT_TOP_LEFT		= ALIGNMENT_BEGIN << 2 	| ALIGNMENT_BEGIN,
	ALIGNMENT_TOP_MIDDLE 	= ALIGNMENT_MIDDLE << 2 | ALIGNMENT_BEGIN,
	ALIGNMENT_TOP_RIGHT 	= ALIGNMENT_END << 2 	| ALIGNMENT_BEGIN,
	ALIGNMENT_CENTER_LEFT	= ALIGNMENT_BEGIN << 2 	| ALIGNMENT_MIDDLE,
	ALIGNMENT_CENTER 		= ALIGNMENT_MIDDLE << 2 | ALIGNMENT_MIDDLE,
	ALIGNMENT_CENTER_RIGHT 	= ALIGNMENT_END << 2 	| ALIGNMENT_MIDDLE,
	ALIGNMENT_BOTTOM_LEFT	= ALIGNMENT_BEGIN << 2 	| ALIGNMENT_END,
	ALIGNMENT_BOTTOM_MIDDLE = ALIGNMENT_MIDDLE << 2 | ALIGNMENT_END,
	ALIGNMENT_BOTTOM_RIGHT 	= ALIGNMENT_END << 2 	| ALIGNMENT_END
};

// Grab the vertical/horizontal part of the 2d alignment
ALIGNMENT_1D Horizontal_Alignment(ALIGNMENT_2D);
ALIGNMENT_1D Vertical_Alignment(ALIGNMENT_2D);
ALIGNMENT_2D Alignment_2D(ALIGNMENT_1D horizontal, ALIGNMENT_1D vertical);

int Align_1D(
int parent_begin, int parent_magnitude, int child_magnitude, ALIGNMENT_1D);
struct nk_vec2 Align_2D(
struct nk_rect parent, struct nk_vec2 child_dimensions, ALIGNMENT_2D);

#endif
